// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
.text

jmp L_undefined_temporary_symbol


movl %eax

movl $0x1234567890, %eax

invalid_inst_name %eax

